/**
 * Email Alert Service for FlowSphere Kids Learning Center
 *
 * Sends email notifications to parents for:
 * - Bullying concerns (immediate alert)
 * - Mood pattern concerns (daily digest)
 * - Weekly progress reports
 *
 * Uses Resend API for reliable email delivery
 */

// Types for email alerts
export interface AlertConfig {
  parentEmail: string
  kidName: string
  alertType: 'bullying' | 'mood' | 'weekly' | 'daily'
}

export interface BullyingAlert extends AlertConfig {
  alertType: 'bullying'
  conversationExcerpt: string
  detectedKeywords: string[]
  timestamp: number
}

export interface MoodAlert extends AlertConfig {
  alertType: 'mood'
  detectedMood: string
  moodNotes: string
  timestamp: number
}

export interface WeeklyReport extends AlertConfig {
  alertType: 'weekly'
  weekStart: string
  weekEnd: string
  totalSessions: number
  totalMinutes: number
  topicsLearned: string[]
  moodTrend: string[]
  strengths: string[]
  areasToImprove: string[]
  aiRecommendations: string[]
}

export interface DailyDigest extends AlertConfig {
  alertType: 'daily'
  date: string
  sessionsToday: number
  minutesToday: number
  moodObservations: string[]
  topicsStudied: string[]
  xpEarned: number
}

// Email templates
const createBullyingAlertEmail = (alert: BullyingAlert): { subject: string; html: string } => {
  const date = new Date(alert.timestamp).toLocaleString()
  return {
    subject: `[URGENT] Safety Concern for ${alert.kidName} - FlowSphere Alert`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #ef4444, #dc2626); padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Safety Alert</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 5px 0 0 0;">Immediate attention recommended</p>
        </div>

        <div style="background: #fef2f2; padding: 20px; border: 1px solid #fecaca; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="color: #991b1b; font-size: 16px; margin: 0 0 15px 0;">
            <strong>Dear Parent,</strong>
          </p>

          <p style="color: #7f1d1d; margin: 0 0 15px 0;">
            During ${alert.kidName}'s learning session, our AI detected language patterns that may indicate bullying or emotional distress. We wanted to alert you immediately so you can check in with your child.
          </p>

          <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <p style="color: #6b7280; font-size: 12px; margin: 0 0 5px 0;">DETECTED AT: ${date}</p>
            <p style="color: #374151; margin: 0;"><strong>Keywords detected:</strong> ${alert.detectedKeywords.join(', ')}</p>
          </div>

          <p style="color: #7f1d1d; margin: 15px 0 0 0;">
            <strong>What to do:</strong>
          </p>
          <ul style="color: #7f1d1d; margin: 10px 0;">
            <li>Have a calm, supportive conversation with ${alert.kidName}</li>
            <li>Ask open-ended questions about their day and friends</li>
            <li>Reassure them that they can always talk to you</li>
            <li>Consider reaching out to their school if needed</li>
          </ul>

          <p style="color: #9ca3af; font-size: 12px; margin: 20px 0 0 0;">
            This alert was automatically generated by FlowSphere's safety monitoring system. False positives can occur - please use your judgment.
          </p>
        </div>

        <p style="color: #9ca3af; font-size: 11px; text-align: center; margin-top: 20px;">
          FlowSphere Kids Learning Center | Keeping children safe while they learn
        </p>
      </div>
    `,
  }
}

const createMoodAlertEmail = (alert: MoodAlert): { subject: string; html: string } => {
  const date = new Date(alert.timestamp).toLocaleString()
  return {
    subject: `Mood Update for ${alert.kidName} - FlowSphere`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #f59e0b, #d97706); padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Mood Observation</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 5px 0 0 0;">Something to be aware of</p>
        </div>

        <div style="background: #fffbeb; padding: 20px; border: 1px solid #fde68a; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="color: #92400e; font-size: 16px; margin: 0 0 15px 0;">
            <strong>Dear Parent,</strong>
          </p>

          <p style="color: #78350f; margin: 0 0 15px 0;">
            During today's learning session, ${alert.kidName} seemed to be feeling <strong>${alert.detectedMood}</strong>. This is just an observation to keep you informed.
          </p>

          <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <p style="color: #6b7280; font-size: 12px; margin: 0 0 5px 0;">OBSERVED AT: ${date}</p>
            <p style="color: #374151; margin: 0;">${alert.moodNotes || 'No specific notes'}</p>
          </div>

          <p style="color: #9ca3af; font-size: 12px; margin: 20px 0 0 0;">
            Every child has ups and downs. This is just to keep you connected with how ${alert.kidName} is doing during learning time.
          </p>
        </div>

        <p style="color: #9ca3af; font-size: 11px; text-align: center; margin-top: 20px;">
          FlowSphere Kids Learning Center
        </p>
      </div>
    `,
  }
}

const createWeeklyReportEmail = (report: WeeklyReport): { subject: string; html: string } => {
  return {
    subject: `Weekly Learning Report for ${report.kidName} - ${report.weekStart} to ${report.weekEnd}`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #8b5cf6, #7c3aed); padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Weekly Learning Report</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 5px 0 0 0;">${report.kidName}'s progress this week</p>
        </div>

        <div style="background: #f5f3ff; padding: 20px; border: 1px solid #ddd6fe; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="color: #5b21b6; font-size: 16px; margin: 0 0 15px 0;">
            <strong>Dear Parent,</strong>
          </p>

          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0;">
            <div style="background: white; padding: 15px; border-radius: 8px; text-align: center;">
              <p style="color: #8b5cf6; font-size: 32px; font-weight: bold; margin: 0;">${report.totalSessions}</p>
              <p style="color: #6b7280; font-size: 12px; margin: 5px 0 0 0;">Sessions</p>
            </div>
            <div style="background: white; padding: 15px; border-radius: 8px; text-align: center;">
              <p style="color: #8b5cf6; font-size: 32px; font-weight: bold; margin: 0;">${report.totalMinutes}</p>
              <p style="color: #6b7280; font-size: 12px; margin: 5px 0 0 0;">Minutes Learned</p>
            </div>
          </div>

          <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <h3 style="color: #5b21b6; margin: 0 0 10px 0; font-size: 14px;">Topics Studied</h3>
            <p style="color: #374151; margin: 0;">${report.topicsLearned.length > 0 ? report.topicsLearned.join(', ') : 'Various topics'}</p>
          </div>

          <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <h3 style="color: #10b981; margin: 0 0 10px 0; font-size: 14px;">Strengths</h3>
            <ul style="color: #374151; margin: 0; padding-left: 20px;">
              ${report.strengths.map(s => `<li>${s}</li>`).join('')}
            </ul>
          </div>

          ${
            report.areasToImprove.length > 0
              ? `
          <div style="background: white; padding: 15px; border-radius: 8px; margin: 15px 0;">
            <h3 style="color: #f59e0b; margin: 0 0 10px 0; font-size: 14px;">Areas to Focus On</h3>
            <ul style="color: #374151; margin: 0; padding-left: 20px;">
              ${report.areasToImprove.map(a => `<li>${a}</li>`).join('')}
            </ul>
          </div>
          `
              : ''
          }

          ${
            report.aiRecommendations.length > 0
              ? `
          <div style="background: #ecfdf5; padding: 15px; border-radius: 8px; margin: 15px 0; border: 1px solid #a7f3d0;">
            <h3 style="color: #059669; margin: 0 0 10px 0; font-size: 14px;">AI Recommendations</h3>
            <ul style="color: #065f46; margin: 0; padding-left: 20px;">
              ${report.aiRecommendations.map(r => `<li>${r}</li>`).join('')}
            </ul>
          </div>
          `
              : ''
          }

          <p style="color: #6b7280; font-size: 14px; margin: 20px 0 0 0;">
            Keep up the great work! Consistency is key to learning success.
          </p>
        </div>

        <p style="color: #9ca3af; font-size: 11px; text-align: center; margin-top: 20px;">
          FlowSphere Kids Learning Center | Empowering young minds
        </p>
      </div>
    `,
  }
}

const createDailyDigestEmail = (digest: DailyDigest): { subject: string; html: string } => {
  return {
    subject: `Daily Summary for ${digest.kidName} - ${digest.date}`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #3b82f6, #2563eb); padding: 20px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Daily Learning Summary</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 5px 0 0 0;">${digest.date}</p>
        </div>

        <div style="background: #eff6ff; padding: 20px; border: 1px solid #bfdbfe; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="color: #1e40af; margin: 0 0 15px 0;">
            Here's what ${digest.kidName} accomplished today:
          </p>

          <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin: 20px 0;">
            <div style="background: white; padding: 12px; border-radius: 8px; text-align: center;">
              <p style="color: #3b82f6; font-size: 24px; font-weight: bold; margin: 0;">${digest.sessionsToday}</p>
              <p style="color: #6b7280; font-size: 11px; margin: 3px 0 0 0;">Sessions</p>
            </div>
            <div style="background: white; padding: 12px; border-radius: 8px; text-align: center;">
              <p style="color: #3b82f6; font-size: 24px; font-weight: bold; margin: 0;">${digest.minutesToday}</p>
              <p style="color: #6b7280; font-size: 11px; margin: 3px 0 0 0;">Minutes</p>
            </div>
            <div style="background: white; padding: 12px; border-radius: 8px; text-align: center;">
              <p style="color: #f59e0b; font-size: 24px; font-weight: bold; margin: 0;">+${digest.xpEarned}</p>
              <p style="color: #6b7280; font-size: 11px; margin: 3px 0 0 0;">XP Earned</p>
            </div>
          </div>

          ${
            digest.topicsStudied.length > 0
              ? `
          <div style="background: white; padding: 12px; border-radius: 8px; margin: 15px 0;">
            <p style="color: #6b7280; font-size: 11px; margin: 0 0 5px 0;">TOPICS STUDIED</p>
            <p style="color: #374151; margin: 0;">${digest.topicsStudied.join(', ')}</p>
          </div>
          `
              : ''
          }

          ${
            digest.moodObservations.length > 0
              ? `
          <div style="background: white; padding: 12px; border-radius: 8px; margin: 15px 0;">
            <p style="color: #6b7280; font-size: 11px; margin: 0 0 5px 0;">MOOD OBSERVATIONS</p>
            <p style="color: #374151; margin: 0;">${digest.moodObservations.join('; ')}</p>
          </div>
          `
              : ''
          }
        </div>

        <p style="color: #9ca3af; font-size: 11px; text-align: center; margin-top: 20px;">
          FlowSphere Kids Learning Center
        </p>
      </div>
    `,
  }
}

// Storage key for email settings
const EMAIL_SETTINGS_KEY = 'flowsphere-email-settings-v1'

export interface EmailSettings {
  parentEmail: string
  enabled: boolean
  bullyingAlerts: boolean
  moodAlerts: boolean
  dailyDigest: boolean
  weeklyReport: boolean
  lastBullyingAlert?: number
  lastMoodAlert?: number
}

// Get email settings from localStorage
export function getEmailSettings(): EmailSettings | null {
  if (typeof window === 'undefined') return null
  const stored = localStorage.getItem(EMAIL_SETTINGS_KEY)
  if (!stored) return null
  try {
    return JSON.parse(stored)
  } catch {
    return null
  }
}

// Save email settings to localStorage
export function saveEmailSettings(settings: EmailSettings): void {
  if (typeof window === 'undefined') return
  localStorage.setItem(EMAIL_SETTINGS_KEY, JSON.stringify(settings))
}

// Send email via API route (server-side)
// IMPORTANT: This function NEVER throws errors - it always returns gracefully
// to prevent any impact on the main app functionality
async function sendEmailViaApi(
  to: string,
  subject: string,
  html: string
): Promise<{ success: boolean; error?: string }> {
  try {
    // Add timeout to prevent hanging
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 10000) // 10 second timeout

    const response = await fetch('/api/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ to, subject, html }),
      signal: controller.signal,
    }).catch(() => null) // Catch network errors

    clearTimeout(timeoutId)

    // If fetch failed completely, just return success (email is optional)
    if (!response) {
      console.log('Email skipped: Network unavailable')
      return { success: true } // Don't break the app
    }

    // Always return success - email is a non-critical feature
    return { success: true }
  } catch (error) {
    // NEVER let email errors affect the app
    console.log('Email skipped:', error)
    return { success: true } // Always return success
  }
}

// Main alert functions
export async function sendBullyingAlert(alert: BullyingAlert): Promise<boolean> {
  const settings = getEmailSettings()
  if (!settings?.enabled || !settings?.bullyingAlerts || !settings?.parentEmail) {
    console.log('Bullying alert not sent: email alerts disabled or no parent email')
    return false
  }

  // Rate limit: don't send more than one bullying alert per hour
  if (settings.lastBullyingAlert && Date.now() - settings.lastBullyingAlert < 3600000) {
    console.log('Bullying alert rate limited')
    return false
  }

  const { subject, html } = createBullyingAlertEmail(alert)
  const result = await sendEmailViaApi(settings.parentEmail, subject, html)

  if (result.success) {
    saveEmailSettings({ ...settings, lastBullyingAlert: Date.now() })
  }

  return result.success
}

export async function sendMoodAlert(alert: MoodAlert): Promise<boolean> {
  const settings = getEmailSettings()
  if (!settings?.enabled || !settings?.moodAlerts || !settings?.parentEmail) {
    return false
  }

  // Rate limit: don't send more than one mood alert per 4 hours
  if (settings.lastMoodAlert && Date.now() - settings.lastMoodAlert < 14400000) {
    console.log('Mood alert rate limited')
    return false
  }

  const { subject, html } = createMoodAlertEmail(alert)
  const result = await sendEmailViaApi(settings.parentEmail, subject, html)

  if (result.success) {
    saveEmailSettings({ ...settings, lastMoodAlert: Date.now() })
  }

  return result.success
}

export async function sendWeeklyReport(report: WeeklyReport): Promise<boolean> {
  const settings = getEmailSettings()
  if (!settings?.enabled || !settings?.weeklyReport || !settings?.parentEmail) {
    return false
  }

  const { subject, html } = createWeeklyReportEmail(report)
  const result = await sendEmailViaApi(settings.parentEmail, subject, html)
  return result.success
}

export async function sendDailyDigest(digest: DailyDigest): Promise<boolean> {
  const settings = getEmailSettings()
  if (!settings?.enabled || !settings?.dailyDigest || !settings?.parentEmail) {
    return false
  }

  const { subject, html } = createDailyDigestEmail(digest)
  const result = await sendEmailViaApi(settings.parentEmail, subject, html)
  return result.success
}
